version: '3.9'
services:
  ctscreener:
    build: .
    ports:
      - "3002:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: npm run dev
